#!/usr/bin/perl -w

# Tool to build and maintain the hash database needed
# for synchronizing.
#
# This tool iterates through the archive to build up the hash value
# of all the


my $script = __FILE__;
my $localdir = ".";
if ($script =~ s/\/[^\/]*$//) {
  $localdir = $script;
}
push @INC, "$localdir/../inc";

require 'photos_util.pm';

pdb_init();

my $gl_verbose = 0;

my $arg = shift;
while (defined($arg)) {
  if ($arg eq "-h" || $arg eq "--help") {
    disp_help();
    exit(0);
  } else {
    print "Unknown argument: $arg\n";
    disp_help();
    exit(0);
  }
  $arg = shift;
}

my $text = put_get_all_hash_text(1);
if ($text ne "") {
  my $hash = phash_do_hash($text);
  phash_set_value("all", "all", $hash);
}
exit(0);

sub disp_help {
  print "Build the hash database. Options:\n";
  print " -h  --help     Display this help text\n";
}
