#!/usr/bin/perl

my $script = __FILE__;
my $localdir = ".";
if ($script =~ s/\/[^\/]*$//) {
  $localdir = $script;
}
push @INC, "$localdir/../cgi-bin";

require "inc_all.pm";

pdb_init();

my $version = "1.1";

$current_version = psys_version();
if ($current_version eq $version) {
  print "Tables have already been created.\n";
  exit(0);
}

if ($current_version eq "1.0") {
  print "Upgrading database from $current_version to $version.\n";
  phash_create_tables();
  psys_set_value("version", $version);
  exit(0);
}

if ($current_version eq "0.9") {
  print "Upgrading database from $current_version to $version.\n";
  psys_create_tables($version);
  phash_create_tables();
  psys_set_value("version", $version);
  exit(0);
}

if ($current_version ne "0.0") {
  print "Unknown current version '$current_version', contact the author.\n";
  exit(0);
}

print "This will create the database tables for the photo archive system.\n";
print "Enter the name and password of the administrator user:\n";

$userId = "";
while ($userId eq "") {
  print "        user ID: ";
  $userId = <STDIN>;
  $userId =~ s/[\r\n]+//sg;
}

$userName = "";
while ($userName eq "") {
  print "      full name: ";
  $userName = <STDIN>;
  $userName =~ s/[\r\n]+//sg;
}

$password = "";
$password2 = "";

while ($password eq "" || $password ne $password2) {
  system("stty -echo");
  print "       password: ";
  $password = <STDIN>;
  $password =~ s/[\r\n]+//sg;
  print "\n";

  print "repeat password: ";
  $password2 = <STDIN>;
  $password2 =~ s/[\r\n]+//sg;
  print "\n";
  system("stty echo");

  if ($password ne $password2) {
    print "Passwords do not match, try again.\n";
  }
}

pusr_create_tables($userId, $userName, $password);
pdb_create_tables();
pses_create_tables();
ppers_create_tables();
psys_create_tables($version);
phash_create_tables();
