#!/usr/bin/perl -w -I .

# Provide an API to get information from the photo archive
use inc_all;

print "Content-type: application/json\n\n";
$data = "";

put_init();
# The logout function effectively "logs in" the guest user
pusr_logout();

my $action = parg_get("action");
if ($action eq "all") {
  $data = get_all_info();
} elsif ($action eq "year") {
  my $year = parg_get("year");
  if ($year ne "") {
    $data = get_year_info($year);
  }
} elsif ($action eq "type") {
  my $type = parg_get("type");
  if ($type ne "") {
    $data = get_type_info($type);
  }
} elsif ($action eq "set") {
  my $setid = parg_get("setid");
  if ($setid ne "") {
    $data = get_set_info($setid);
  }
} elsif ($action eq "image") {
  my $imageid = parg_get("imageid");
  if ($imageid ne "") {
    $data = get_image_info($imageid);
  }
}

if ($data eq "") {
  print "{\"error\":\"No Action or unrecognized action\"}";
} else {
  print $data;
}

exit(0);

sub json_out {
  my $name = $_[0];
  my $value = $_[1];

  my $out = "";
  $out .= "\"$name\":\"";
  $value =~ s/"/&quot;/g;
  $out .= "$value\"";

  return $out;
}

sub get_all_info {
  my $out = "";

  $out .= "{\n";

  $out .= "\"years\":[\n";
  my $first_year = pcom_first_year();
  my $last_year = pcom_last_year();
  for (my $i = $first_year; $i <= $last_year; $i++) {
    if ($i != $first_year) {
      $out .= ",\n";
    }
    $out .= "{\n";
    $out .= json_out("year", $i) . ",\n";
    $out .= json_out("description", $i) . "\n";
    $out .= "}";
  }
  $out .= "],\n";

  $out .= "\"specials\":[\n";
  $out .= "{\n";
  $out .= json_out("year", "9999") . ",\n";
  $out .= json_out("description", "Special Photos") . "\n";
  $out .= "},{\n";
  $out .= json_out("type", "d") . ",\n";
  $out .= json_out("description", "Photos and Slides by my Parents") . "\n";
  $out .= "}\n";
  $out .= "]\n";
  $out .= "}\n";

  return $out;
}

sub get_year_info {
  my $year = $_[0];
  my $out = "";

  $out .= "{\n";
  $out .= json_out("year", $year) . ",\n";

  $out .= "\"sets\":[\n";
  my $iter = pdb_iter_set_new();
  pdb_iter_filter_category($iter, put_types());
  pdb_iter_filter_year($iter, $year);
  my $setid = "";
  $setid = pdb_iter_prev($iter);
  my $isFirst = 1;
  while ($setid ne "") {
    my $title = pdb_get_settitle($setid);
    if ($title eq "") {
      $title = "Film $setid";
    }
    my $datetime = pdb_get_setdatetime($setid);
    my $descr = pdb_get_setdescription($setid);

    if (!$isFirst) {
      $out .= ",\n";
    }
    $out .= "{\n";
    $out .= json_out("setid", $setid) . ",\n";
    $out .= json_out("title", $title) . ",\n";
    $out .= json_out("datetime", $datetime) . ",\n";
    $out .= json_out("description", $descr) . ",\n";
    $out .= "}";
    $isFirst = 0;
    $setid = pdb_iter_next($iter);
  }
  $out .= "]\n";

  $out .= "}\n";

  return $out;
}

sub get_type_info {
  my $type = $_[0];
  my $out = "";

  $out .= "{\n";
  $out .= "\"type\":\"$type\",\n";

  $out .= "\"sets\":[\n";
  my $iter = pdb_iter_set_new();
  pdb_iter_filter_category($iter, $type);
  my $setid = pdb_iter_next($iter);

  my $isFirst = 1;
  while ($setid ne "") {
    my $title = pdb_get_settitle($setid);
    if ($title eq "") {
      $title = "Film $setid";
    }
    my $datetime = pdb_get_setdatetime($setid);
    my $descr = pdb_get_setdescription($setid);

    if (!$isFirst) {
      $out .= ",\n";
    }
    $out .= "{\n";
    $out .= json_out("setid", $setid) . ",\n";
    $out .= json_out("title", $title) . ",\n";
    $out .= json_out("datetime", $datetime) . ",\n";
    $out .= json_out("description", $descr) . "\n";
    $out .= "}";
    $isFirst = 0;
    $setid = pdb_iter_next($iter);
  }
  $out .= "]\n";

  $out .= "}\n";

  return $out;
}

sub get_set_info {
  my $setid = $_[0];
  my $out = "";

  my $category = pdb_get_setcategory($setid);
  if (!pdb_set_exists($setid)
    || (($category ne "") && !pusr_allowed($category))) {
    return "{\"error\":\"Not found\"}\n";
  }

  $out .= "{";

  my $title = pdb_get_settitle($setid);
  my $datetime = pdb_get_setdatetime($setid);
  my $description = pdb_get_setdescription($setid);
  my $comment = pdb_get_setcomment($setid);
  my $copyright = pdb_get_setcopyright($setid);
  my $year = pdb_get_setyear($setid);

  $out .= json_out("title", $title) . ",\n";
  $out .= json_out("datetime", $datetime) . ",\n";
  $out .= json_out("description", $description) . ",\n";
  $out .= json_out("copyright", $copyright) . ",\n";
  $out .= json_out("year", $year) . ",\n";

  my $iter = pdb_iter_new($setid, 40);
  pdb_iter_filter_setid($iter, $setid);
  pdb_iter_filter_category($iter, put_types());
  pdb_iter_filter_min_quality($iter, put_quality());
  my $imageid = pdb_iter_next($iter);
  my $imagecount = 0;

  $out .= "\"photos\":[";
  my $photoInfo = "\"photoInfo\":[";
  my $isFirst = 1;
  while (pcom_get_set($imageid) le $setid) {
    # Note: Because the sort ID uses GMT, it is possible to get images
    # from the previous day when iterating through the sets. Skip
    # those.
    if (pcom_get_set($imageid) lt $setid) {
      if (pcom_is_digital($imageid)) {
        $imageid = pdb_iter_next($iter);
        next;
      } else {
        # if not a digital photo, break out of the loop
        last;
      }
    }

    if (!$isFirst) {
      $out .= ",";
      $photoInfo .= ",\n";
    }
    $out .= "\"$imageid\"";

    my $orientation = pdb_get_orientation($imageid);
    my $title = pdb_get_title($imageid);
    my $description = pdb_get_description($imageid);

    $photoInfo .= "{\n";
    $photoInfo .= json_out("imageId", $imageid) . ",\n";
    $photoInfo .= json_out("title", $title) . ",\n";
    $photoInfo .= json_out("description", $description) . ",\n";
    $photoInfo .= json_out("orientation", $orientation) . "\n";
    $photoInfo .= "}";
    $isFirst = 0;
    $imageid = pdb_iter_next($iter);
  }
  $out .= "],\n";

  $photoInfo .= "]\n";
  $out .= $photoInfo;
  $out .= "}\n";

  return $out;
}

sub get_image_info {
  my $imageid = $_[0];
  my $out = "";

  my $category = pdb_get_category($imageid);
  if (!pdb_image_exists($imageid)
    || (($category ne "") && !pusr_allowed($category))) {
    return "{\"error\":\"Not found\"}\n";
  }

  my $category = pdb_get_category($imageid);
  my $copyright = pdb_get_copyright($imageid);
  my $datetime = pdb_get_datetime($imageid);
  my $description = pdb_get_description($imageid);
  my $latlong = pdb_get_latlong($imageid);
  my $location = pdb_get_location($imageid);
  my $orientation = pdb_get_orientation($imageid);
  my $persons = pdb_get_persons($imageid);
  my $person_id_list = ppers_get_persons_in_image($imageid);
  my $quality = pdb_get_quality($imageid);
  my $title = pdb_get_title($imageid);
  my $year = pdb_get_year($imageid);

  my $fname = pfs_get_edited_location($imageid);
  if ($fname eq "") {
    $fname = pfs_get_orig_location($imageid);
  }

  # Get the (original) width and height of the image, to calculate display
  # size for "freeform" images.
  my ($width, $height) = pfs_get_file_dimensions($fname);

  $out .= "{\n";
  $out .= json_out("category", $category) . ",\n";
  $out .= json_out("copyright", $copyright) . ",\n";
  $out .= json_out("datetime", $datetime) . ",\n";
  $out .= json_out("description", $description) . ",\n";
  $out .= json_out("height", $height) . ",\n";
  $out .= json_out("latlong", $latlong) . ",\n";
  $out .= json_out("location", $location) . ",\n";
  $out .= json_out("orientation", $orientation) . ",\n";
  $out .= json_out("persons", $persons) . ",\n";
  $out .= json_out("person_id_list", $person_id_list) . ",\n";
  $out .= json_out("quality", $quality) . ",\n";
  $out .= json_out("title", $title) . ",\n";
  $out .= json_out("width", $width) . ",\n";
  $out .= json_out("year", $year) . "\n";

  $out .= "}\n";

  return $out;
}
