#!/usr/bin/perl -I .

use inc_all;
put_init();

my $movieid = parg_get("mov");

my $srcname = pfs_get_raw_location($movieid);
my $fname = pfs_get_large_location($movieid);
$fname =~ s/\.jpg$/.mp4/;

if (! -f $fname) {
    my $cmd = pfs_cmd_large_movie($movieid);
    system($cmd);
}

print "Content-type: video/mp4\n\n";
my $data = "";
open(FILE, "<$fname");
binmode(FILE);
binmode(STDOUT);
while (<FILE>) {
    print $_;
    # $data .= $_;
}
close FILE;

# print $data;
