#!/usr/bin/perl -I .

use inc_all;
put_init();

print "Content-type: video/mp4\n\n";

my $movieid = parg_get("mov");

my $srcname = pfs_get_raw_location($movieid);

# To determine the target name, even if the movie is not there, get the
# name of what a large-size image _should_ be, and replace the extension.
my $fname = pfs_get_buffer_location($movieid, $PCOM_LARGE);
$fname =~ s/\.jpg$/.mp4/;

if (!-f $fname) {
  my $orientation = pdb_getorie($movieid);
  my $cmd = pfs_cmd_large_movie($movieid);
  system($cmd);
}

my $data = "";
open(FILE, "<$fname");
binmode(FILE);
binmode(STDOUT);
while (<FILE>) {
  print $_;
  # $data .= $_;
}
close FILE;

# print $data;
