#!/usr/bin/perl

my $script = __FILE__;
my $localdir = ".";
if ($script =~ s/\/[^\/]*$//) {
  $localdir = $script;
}
push @INC, "$localdir/../inc";

require "photos_util.pm";

put_init();
put_restore_session();

my $start = get_value("start");
my $end = get_value("end");
my $image = get_value("image");
my $do_settings = get_value("doSettings");

# auto-refresh, must be whole number
my $auto = get_value("auto");
if (!($auto =~ /^\d+$/)) {
  $auto = "";
}

if ($do_settings ne "") {
  display_settings($image, $start, $end, $auto);
  exit(0);
}

if ($image eq "") {
  $image = $start;
  if ($image eq "") {
    # Without a start, start at the beginning
    $image = "00000000";
  }
}

if ( ($image =~ /^\d\d\d\d\d\d\d\d$/)
  || ($image =~ /^\w\d\d$/)) {
  # Image is a set; use get next to get the first of the set
  $image = get_next_image($image);
}

my $prev = get_prev_image($image);
my $next = get_next_image($image);

my $is_next_end = 0;
if ($next eq "" || $next eq $image) {
  $is_next_end = 1;
} elsif ($end ne "") {
  # If $end is blank, go all the way to the end
  if ( ($end =~ /^\d\d\d\d\d\d\d\d$/)
    || ($end =~ /^\w\d\d$/)) {
    # End is a set; check against the set name
    my $imageset = "";
    if ($next =~ /^(\w\d\d)\d\d\w?$/) {
      $imageset = $1;
    } elsif ($next =~ /^(\d\d\d\d\d\d\d\d)-\d\d\d\d\d\d\w?$/) {
      $imageset = $1;
    }
    if ($imageset gt $end) {
      $is_next_end = 1;
    }
  } else {
    if ($next gt $end) {
      $is_next_end = 1;
    }
  }
}

if ($is_next_end) {
  # Reached the end; wrap back to the start
  $next = $start;
  if ($next eq "") {
    $next = "00000000";
  }
  if ( ($next =~ /^\d\d\d\d\d\d\d\d$/)
    || ($next =~ /^\w\d\d$/)) {
    # Start is a set; use get next to get the first of the set
    $next = get_next_image($next);
  }
}

my $is_prev_end = 0;
if ($prev eq "" || $prev eq $image) {
  $is_prev_end = 1;
} elsif ($start ne "") {
  # If $start is blank, go all the way to the beginning
  if ($prev lt $start) {
    $is_prev_end = 1;
  }
}

if ($is_prev_end) {
  # Reached the end; wrap back to the end
  $prev = $end;
  if ($prev eq "") {
    $prev = get_prev_image("21991231-235959");
  } elsif ($prev =~ /^\d\d\d\d\d\d\d\d$/) {
    $prev = get_prev_image("$prev-235959z");
  } elsif ($next =~ /^\w\d\d$/) {
    $prev = get_prev_image("${prev}99z");
  }
}

display_img($image, $prev, $next, $start, $end, $auto);
exit(0);

sub custom_header {
  # Build the header elements. This contains custom styles and the script to
  # handle the body click.
  my $header = "";

  $header .= "<style>\n";
  $header .= "html {\n";
  $header .= "  height: 100%;\n";
  $header .= "}\n";
  $header .= "div.prevClick {\n";
  $header .= "  position: absolute;\n";
  $header .= "  top: 0;\n";
  $header .= "  left: 0;\n";
  $header .= "  width: 39%;\n";
  $header .= "  height: 100%;\n";
  $header .= "  cursor: pointer;\n";
  $header .= "}\n";
  $header .= "div.nextClick {\n";
  $header .= "  position: absolute;\n";
  $header .= "  top: 0;\n";
  $header .= "  right: 0;\n";
  $header .= "  width: 59%;\n";
  $header .= "  height: 100%;\n";
  $header .= "  cursor: pointer;\n";
  $header .= "}\n";
  $header .= "
  html {
    height: 100%;
  }
  body.slideshow {
    font-size: 16pt;
    line-height: 150%;
  }
  body.slideshow form {
    margin: 1em;
  }
  div.no-image {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translateY(-50%) translateX(-50%);
  }
  div.icons {
    text-align: right;
    font-size: 250%;
    padding: 0.2em;
    z-index: 10;
  }
  div.icons a {
    position: relative;
    display: inline-block;
    margin: 0.1em;
    border-radius: 1em;
    background-color: rgba(0, 0, 0, 0.25);
  }
  div.icons a i {
    display: inline-block;
    font-size: 50%;
    padding: 0.5em;
    color: #fff;
  }
  div.icons a i.fa-stop {
    color: #f00;
  }
  div.icons a i.fa-play {
    color: #0f0;
  }
  div.icons a:hover i {
    color: #c00;
  }
  ";
  $header .= "</style>\n";

  $header .= "<script>\n";
  $header .= "function go(event, url) {\n";
  $header .= "  event.preventDefault();\n";
  $header .= "  location=url;\n";
  $header .= "  return false;\n";
  $header .= "};\n";
  $header .= "</script>\n";

  pht_add_header($header);
}

sub display_img {
  my $image = $_[0];
  my $prev = $_[1];
  my $next = $_[2];
  my $start = $_[3];
  my $end = $_[4];
  my $auto = $_[5];

  # Default size to "m5", which is about 1920x1080, which should be a good
  # default for most phone, tablet and laptop displays
  my $size = "m5";

  my $image_url = "phimg?$size=$image&orientation=landscape";

  my $content = "";

  my $show_image = 1;

  # If the image doesn't exist, give an error
  if (!pdb_image_info($image)) {
    $show_image = 0;
  }

  # If no category defined for the image, give an error
  my $category = pdb_get_category($image);
  if ($category eq "") {
    $show_image = 0;
  }

  # If the current user isn't alowed to see the image, give an error
  if (!pusr_allowed($PUSR_SEE . $category)) {
    $show_image = 0;
  }

  custom_header();

  my $url_suffix = "";
  $url_suffix .= "&start=$start" if ($start ne "");
  $url_suffix .= "&end=$end" if ($end ne "");
  $url_suffix .= "&auto=$auto" if ($auto ne "");

  my $curr_url = "phslideshow?image=$image$url_suffix";
  my $prev_url = "phslideshow?image=$prev$url_suffix";
  my $next_url = "phslideshow?image=$next$url_suffix";

  if (pdb_get_type($image) ne "MOV") {
    if ($show_image) {
      my $header = "";
      $header .= "<style>\n";
      $header .= "body.slideshow {\n";
      $header .= "  background-image: url('$image_url');\n";
      $header .= "}\n";
      $header .= "</style>\n";
      pht_add_header($header);
    }
  }

  pht_add_header(
    "<script src='https://kit.fontawesome.com/c54eb67fb4.js' crossorigin='anonymous'></script>"
  );

  if ($auto ne "" && $auto > 0) {
    pht_set_refresh("$auto; url='$next_url'");
  }

  pht_page_start(0, 0);

  print "<body class='slideshow'>\n";
  print "<div class='prevClick' onclick='go(event, \"$prev_url\")'>";
  print "&nbsp;</div>\n";
  print "<div class='nextClick' onclick='go(event, \"$next_url\")'>";
  print "&nbsp;</div>\n";

  print "<div class='icons'>";
  print "<a href='phslideshow?doSettings=1&image=$image&$url_suffix'>";
  print "<i class='fas fa-cog' title='Settings'></i>";
  print "</a><br/>";
  if ($auto ne "" && $auto > 0) {
    my $auto_url = $curr_url;
    $auto_url =~ s/&auto=\d+//;
    print "<a href='$auto_url'>";
    print "<i class='fas fa-stop' title='Stop'></i>";
    print "</a><br/>";
  } else {
    my $auto_url = $curr_url;
    $auto_url .= "&auto=5";
    print "<a href='$auto_url'>";
    print "<i class='fas fa-play' title='Auto Slideshow'></i>";
    print "</a><br/>";
  }
  print "</div>\n";
  if ((pdb_get_type($image) eq "MOV") && $show_image) {
    print "<video width='80%' height='80%' controls poster='phimg?mov=$image'>";
    print "<source src='phmov?mov=$image' type='video/mp4'/>";
    print "</video>";
  }
  if (!$show_image) {
    print "<div class='no-image'>This image is not available.</div>\n";
  }
  # Pre-load the next image, to make loading faster
  print "<img src='./phimg?$size=$next&orientation=landscape' width='1' ";
  print " height='1' border='0'>\n";

  pht_page_end(0);
}

sub display_settings {
  my $image = $_[0];
  my $start = $_[1];
  my $end = $_[2];
  my $auto = $_[3];

  my $url_suffix = "";
  $url_suffix .= "&start=$start" if ($start ne "");
  $url_suffix .= "&end=$end" if ($end ne "");
  $url_suffix .= "&auto=$auto" if ($auto ne "");

  my $url = "phslideshow?image=$image$url_suffix";

  custom_header();

  pht_page_start(0, 0);

  print "<body class='slideshow'>\n";
  print "<form method='GET' target='phslideshow'>\n";
  print "<h1>Slideshow Settings</h1>\n";
  print "<p>The <em>Photo Archive Slide Show Tool</em> is used to produce a\n";
  print "slide show of photos in the photo archive. By default, the slide\n";
  print "show starts at the beginning and goes on to the end of the archive.\n";
  print "The settings on this page can change this default.</p>\n";
  print "<input type='hidden' name='image' value='$image' />\n";
  print "<p><b>Start</b>: <input name='start' value='$start' /></p>\n";
  print "<p><b>End</b>: <input name='end' value='$end' /></p>\n";
  print "<p><b>Auto</b>: <input name='auto' value='$auto' /></p>\n";
  print "<p><input type='submit' value='Start' />\n";
  print "<input type='submit' value='Cancel' onclick='go(event, \"$url\")'/>";
  print "</p>\n";
  print "<p>Explanation:</p>\n";
  print "<ul>\n";
  print "<li><b>Start</b> is the image or set ID where to start the\n";
  print "slideshow.</li>\n";
  print "<li><b>End</b> is the image or set ID where to end the\n";
  print "slideshow.</li>\n";
  print "<li><b>Auto</b>, if set, is the time (in seconds) when to\n";
  print "automatically advance to the next image.</li>\n";
  print "</form>\n";
  pht_page_end(0);
}

sub get_value {
  my $varname = $_[0];
  my $default = $_[1];
  if (!defined($default)) {
    $default = "";
  }

  my $value = $default;

  if (parg_exists($varname)) {
    $value = parg_get($varname);
    # Note: using value from session is disabled for now, it doesn't work
    # through the proxy
    # # Specific value specified; save it in the session
    # pses_set($varname, $value);
    # } else {
    #   # No value specified; get one from the session
    #   my $temp = pses_get($varname);
    #   if ($temp ne "") {
    #     $value = $temp;
    #   }
  }
  return $value;
}

sub set_value {
  my $varname = $_[0];
  my $value = $_[1];
  pses_set($varname, $value);
  return $value;
}

sub get_next_image {
  my $imageid = $_[0];

  my $user = $PUSR_GUEST_ACCOUNT;

  # Set the filters appropriately
  my $types = get_types($user);
  my $min_quality = get_value("min_quality");
  if ($min_quality eq "") {
    $min_quality = get_quality($user);
  }

  # Determine the next image

  my $class = put_get_class($imageid);

  my $iter = pdb_iter_new($imageid);
  pdb_iter_filter_category($iter, $types);
  pdb_iter_filter_min_quality($iter, $min_quality);

  my $next = pdb_iter_next($iter);
  if ($next eq $imageid) {
    $next = pdb_iter_next($iter);
  }
  pdb_iter_done($iter);

  if (put_get_class($next) ne $class) {
    # different class, so do not walk over into it
    $next = "";
  }
  return $next;
}

sub get_prev_image {
  my $imageid = $_[0];

  my $user = $PUSR_GUEST_ACCOUNT;

  # Set the filters appropriately
  my $types = get_types($user);
  my $min_quality = get_value("min_quality");
  if ($min_quality eq "") {
    $min_quality = get_quality($user);
  }

  # Determine the previous image

  my $class = put_get_class($imageid);

  my $iter = pdb_iter_new($imageid);
  pdb_iter_filter_category($iter, $types);
  pdb_iter_filter_min_quality($iter, $min_quality);

  my $prev = pdb_iter_previous($iter);
  if ($prev eq $imageid) {
    $prev = pdb_iter_previous($iter);
  }
  pdb_iter_done($iter);

  if (put_get_class($next) ne $class) {
    # different class, so do not walk over into it
    $prev = "";
  }
  return $prev;
}

sub get_types {
  my $effective_user = $_[0];

  if ($effective_user ne "") {
    # Use the edit function to retrieve the settings for the
    # "random" user
    pusr_load($effective_user);
  }

  my $types = put_types();

  return $types;
}

sub get_quality {
  my $effective_user = $_[0];

  if ($effective_user ne "") {
    # Use the edit function to retrieve the settings for the
    # "random" user
    pusr_load($effective_user);
  }

  my $quality = put_quality();

  return $quality;
}
